name: 'Semver Release'
description: 'Automatically create Semver compliant tags or releases based on PR labels'
author: 'Kévin Gomez'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  release_branch:
    description: 'Branch to tag'
    required: true
    default: master

  release_strategy:
    description: 'Release strategy'
    required: true
    default: release

  tag_format:
    description: 'Format used to create tags'
    required: true
    default: 'v%major%.%minor%.%patch%'

  tag:
    description: 'Tag to use'
    required: false

  base_host:
    description: 'GitHub Enterprise Server base host'
    required: false
    default: 'api.github.com'

  upload_host:
    description: 'GitHub Enterprise Server upload host'
    required: false
    default: 'upload.github.com'

outputs:
  tag:
    description: 'The newly created tag'

runs:
  using: 'docker'
  image: 'docker://cloudcrafts/semver-release-action:v1.3.3'
  args:
    - ${{ inputs.release_branch }}
    - ${{ inputs.release_strategy }}
    - ${{ inputs.tag }}
    - ${{ inputs.tag_format }}
    - ${{ inputs.base_host }}
    - ${{ inputs.upload_host }}
