name: 'Semver Release'
description: 'Automatically create Semver compliant tags or releases based on PR labels'
author: 'Kévin Gomez'

branding:
  icon: 'tag'
  color: 'green'

inputs:
  release_branch:
    description: 'Branch to tag'
    required: true
    default: master

  release_strategy:
    description: 'Release strategy'
    required: true
    default: release

  default_increment:
    description: 'Default increment (skip/patch/minor/major)'
    required: true
    default: skip

  tag_format:
    description: 'Format used to create tags'
    required: true
    default: 'v%major%.%minor%.%patch%'

  tag:
    description: 'Tag to use'
    required: false

outputs:
  tag:
    description: 'The newly created tag'

runs:
  using: 'docker'
  image: 'docker://kphoen/semver-release-action:v1.3.1'
  args:
    - ${{ inputs.release_branch }}
    - ${{ inputs.release_strategy }}
    - ${{ inputs.tag }}
    - ${{ inputs.tag_format }}
    - ${{ inputs.default_increment }}
